language: cpp
sudo: required

git:
  depth: 10

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/hlprasu/swig-trusty-backports/ubuntu trusty main'
    packages:
      - libssl-dev
      - python-dev
      - scons
      - swig3.0

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install swig
    brew outdated openssl || brew upgrade openssl
    brew outdated cmake || brew upgrade cmake
  fi
- python -V

script:
- ./travis.sh


